<?php

/**
 * @file
 * Avalara CertCapture service integration from Avalara, Inc.
 */

/**
 * Implements hook_menu().
 */
function commerce_avalara_cert_menu() {
  $items = array();

  $items['admin/commerce/config/avalara-cert'] = array(
    'title' => 'Avalara CertCapture ',
    'description' => 'Avalara CertCapture Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_avalara_cert_settings_form'),
    'file' => 'includes/commerce_avalara_cert.admin.inc',
    'access arguments' => array('administer commerce_avalara_cert'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['user/%user/tax-certificates'] = array(
    'title' => 'Tax certificates',
    'page callback' => 'commerce_avalara_cert_user_page',
    'page arguments' => array(1),
    'access callback' => 'commerce_avalara_cert_user_page_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/commerce_avalara_cert.user.inc',
    'weight' => 20,
  );

  $items['avalara-cert/%/download'] = array(
    'page callback' => 'commerce_avalara_cert_download',
    'page arguments' => array(1),
    'access callback' => 'commerce_avalara_cert_download_access',
    'access arguments' => array(1),
    'file' => 'includes/commerce_avalara_cert.user.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Access callback: determines access to the "Tax certificates" user page.
 */
function commerce_avalara_cert_user_page_access($account) {
  if (user_access('administer commerce_avalara_cert')) {
    return TRUE;
  }
  global $user;

  // If the user doesn't have the "administer commerce_avalara_cert" permission
  // & passed account is not the same as the logged in user, return FALSE.
  if ($account->uid != $user->uid) {
    return FALSE;
  }

  return user_access('view own tax certificates');
}


/**
 * Access callback: determines access to download certificate.
 */
function commerce_avalara_cert_download_access($account) {
  global $user;
  return (!user_is_anonymous() && $account->uid == $user->uid);
}

/**
 * Implements hook_theme().
 */
function commerce_avalara_cert_theme($existing, $type, $theme, $path) {
  return array(
    'commerce_avalara_cert_user_certificates' => array(
      'variables' => array(
        'customer_code' => NULL,
        'table' => '',
      ),
      'template' => 'commerce-avalara-cert-user-certificates',
      'path' => $path . '/theme',
    ),
  );
}

/**
 * Preprocess variables for commerce-avalara-cert-user-certificates.tpl.php.
 */
function template_preprocess_commerce_avalara_cert_user_certificates(&$variables) {
  $variables['table'] = array(
    '#theme' => 'table',
    '#header' => array(
      t('State'),
      t('Signed date'),
      t('Expiration date'),
      t('Status'),
      t('View'),
    ),
    '#rows' => array(),
  );
  $empty_message = t('No tax certificates could be found.');

  if (empty($variables['customer_code'])) {
    $variables['table']['#empty'] = $empty_message;
    return;
  }

  // Add the customer code as a JS setting.
  drupal_add_js(array('commerce_avalara_cert' => array('customer_number' => $variables['customer_code'])), 'setting');

  // Consider the JS SDK as non present by default.
  $sdk_present = FALSE;
  $registration_key = variable_get('commerce_avalara_cert_registration_key', '');
  $client_id = commerce_avalara_cert_client_id();

  // Add the JS SDK and the "Renew" table header in case we have a registration
  // key.
  if (!empty($registration_key) && !empty($client_id)) {
    $sdk_present = TRUE;
    $client_id = check_plain($client_id);
    $registration_key = check_plain($registration_key);
    $variables['table']['#header'][] = t('Renew');
    drupal_add_library('system', 'ui.dialog');
    drupal_add_js(drupal_get_path('module', 'commerce_avalara_cert') . '/js/commerce_avalara_cert.user.js');
    drupal_add_js("https://app.certcapture.com/gencert2/js?cid=$client_id&key=$registration_key", 'external');
  }

  try {
    $avalara = commerce_avalara_cert_object();
    $exempt_reasons = $avalara->customersGetExemptReasons($variables['customer_code']);

    foreach ($exempt_reasons as $exempt_reason) {
      $tax_code_name = $exempt_reason['actual_tax_code']['name'];

      $status = t('Valid');
      // Logic stolen from the Avalara code sample.
      if (substr($tax_code_name, 0, 8) == 'EXPOSURE' || substr($tax_code_name, 0, 7) == 'TAXABLE') {
        if (substr($tax_code_name, 0, 8) == "EXPOSURE"){
          $status = substr($tax_code_name, 10, 25);
        }
        else {
          $status = t('TAXABLE');
        }
      }

      $row = array(
        $exempt_reason['exposure_zone']['name'],
        $exempt_reason['certificate']['signed_date'],
        $exempt_reason['certificate']['expiration_date'],
        $status,
        l('View', 'avalara-cert/' . $exempt_reason['certificate']['id'] . '/download'),
      );

      // If the SDK is present, add the renew link.
      if ($sdk_present) {
        $renew_link_options = array(
          'external' => TRUE,
          'attributes' => array(
            'data-state' => $exempt_reason['exposure_zone']['name'],
            'class' => array(
              'commerce-avalara-cert-renew',
            ),
          ),
        );
        $row[] = l('Renew', '#', $renew_link_options);
      }

      $variables['table']['#rows'][] = $row;
    }
  }
  catch (Exception $e) {
  }

  if (empty($variables['table']['#rows'])) {
    $variables['table']['table']['#empty'] = t('No tax certificates could be found.');
  }
}

/**
 * Implements hook_permission().
 */
function commerce_avalara_cert_permission() {
  return array(
    'administer commerce_avalara_cert' => array(
      'title' => t('Administer Avalara CertCapture'),
      'description' => t('Allows users to configure Commerce Avalara CertCapture.'),
      'restrict access' => TRUE,
    ),
    'view own tax certificates' => array(
      'title' => t('View own tax certificates'),
      'description' => t('Allows users to view their own tax certificates.'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Returns the Avalara CertCapture username.
 */
function commerce_avalara_cert_username() {
  return variable_get('commerce_avalara_cert_username', '');
}

/**
 * Returns the Avalara CertCapture password.
 */
function commerce_avalara_cert_password() {
  return variable_get('commerce_avalara_cert_password', '');
}

/**
 * Returns the configured client_id.
 */
function commerce_avalara_cert_client_id() {
  return variable_get('commerce_avalara_cert_client_id', '');
}

/**
 * Returns a statically cached instance of an AvalaraCert object.
 *
 * @param string $api_key
 *   The API key to use to submit requests to the Avatax API.
 * @param string $client_id
 *   The client_id, accessible from the "Company settings" page.
 *
 * @return AvalaraCert|bool.
 *   The constructed object or FALSE if the library could not be loaded.
 */
function commerce_avalara_cert_object($api_key = '', $client_id = '') {
  $avalara = &drupal_static(__FUNCTION__, array());

  // If the API key wasn't provided.
  if (empty($api_key)) {
    $username = commerce_avalara_cert_username();
    $password = commerce_avalara_cert_password();

    if (!empty($username) && !empty($password)) {
      $api_key = base64_encode("$username:$password");
    }
    else {
      return FALSE;
    }
  }

  // Defaults the client_id to the one configured if not specified.
  $client_id = $client_id ? $client_id : commerce_avalara_cert_client_id();

  if (empty($client_id)) {
    return FALSE;
  }

  if (!isset($avalara[$api_key])) {
    $logger = NULL;
    $headers = array(
      'x-client-id' => $client_id,
      // Use the customer_number for reference.
      'x-customer-primary-key' => 'customer_number',
    );

    // Specify the logger if the logging was enabled.
    if (variable_get('commerce_avalara_cert_logging', FALSE)) {
      $logger = 'watchdog';
    }

    $avalara[$api_key] = new AvalaraCert($api_key, $logger, $headers);
  }

  return $avalara[$api_key];
}

/**
 * Implements hook_field_access().
 */
function commerce_avalara_cert_field_access($op, $field, $entity_type, $entity, $account) {
  // Hide the customer code field.
  if ($field['field_name'] == 'commerce_avalara_customer_code' && $op == 'edit') {
    return user_access('administer commerce_avalara_cert', $account);
  }
}
